### ISSUE TITLE
使用AlliN进行全端口扫描无法扫出数据库端口

### ISSUE THREAD

**Issue by helloyw** [P1-Team/AlliN#14]
使用AlliN v2.4.0进行全端口扫描无法扫出数据库端口
命令：`python AlliN.py --host 127.0.0.1 -p- -t 500` 开放redis 6379端口但是没有扫描出来。

**Comment by Like0x** [comment]
这个问题比较难以确定真实问题，和网络环境质量有较大关系，可以尝试降低线程看看能不能扫出来，或者配合--ctimeout 使用。

**Comment by helloyw** [comment]
> 这个问题比较难确定是真实问题，而且网络环境质量有很大关系，可以尝试降低线路看看不能扫出来，或者配合--ctimeout。

redis我再试试。

1098 rmi端口也没扫到与识别出来，希望能加入namp指纹

**Comment by helloyw** [comment]
> AlliN脚本中的指纹属于静态指纹（硬编码），所以它只会根据知名端口返回相关服务名，不会进行指纹的识别。使用nmap的指纹进行配合识别，这个会考虑的，感谢意见。

三克油歪瑞马驰
