### ISSUE TITLE
大师傅能一直更新下去吗

### ISSUE THREAD

**Issue by JackeyLov5** [P1-Team/AlliN#15]
我是该项目的忠实粉丝，极高的自由度和近乎完美的功能。
1.但是突然我发现如果目标太多 给他一个所有目标根域名的列表就不能调用模块去批量查询
python3 Allin.py -f y111.txt -m sfscan
这一点在红蓝对抗中比较节省时间
2.hunter平台也可以弄一个模式出来跟fscan 模式一样就好，如果能优化一些哪就更完美了
3.能否支持输出csv和xslx格式的文件呢
不管更不更新都先谢谢大佬写出这么好用的工具

**Comment by Like0x** [comment]
1. 对于第一个问题，之前的替代方案是使用 逗号进行多个域名的分割，或者使用bash脚本(在readme前部分有提到)批量调用AlliN，这显然不是一个优雅的方案，但可以应急。师傅说的-f 的参数进行调用,这个需求我们会在下个版本进行更新。
```bash
python AlliN.py -q 'domain="xx.com"' --host xxx.com,yyy.com -m sfscan
```
2. hunter 因为积分制度的问题, 一直没有添加，不过会考虑添加。
3. 目前输出的格式可选的另一种为json，csv 和 xslx的需求还没有碰到场景，师傅可以列举看看。

很感谢师傅能够喜欢这款工具, AlliN就是一个小工具他不为追求一把梭,只是让自己用的顺手。AlliN会持续的更新下去，因为目前工具完善程度已经可以完成大部分工作任务，所以更新较为缓慢，有相关需求可以提issue，看到后我们会认真考虑进行功能迭代。

**Comment by JackeyLov5** [comment]
csv没在readme看到以为不行 感谢师傅认真解答 Allin真的很不错！期待更新

**Comment by christasa** [comment]
AlliN暂时还只支持txt和json的格式。csv和xslx的格式要求暂时还没有需要的场景，如果师傅需要csv这些格式可否给出使用的场景呢

**Comment by christasa** [comment]
查看结果的话个人认为终端直接输出的内容会更加清晰。关于提取内容的方面，师傅也可以通过对json文件解析来进行域名进行提取，或者使用shell命令`awk -F ' | ' '{print $2}'  res_alivedomain.txt | awk '/./ {print}'` 获取到域名。

非常感谢师傅的喜欢以及宝贵的建议，csv和xlsx格式我们会在后续进行深度讨论，`-f`参数的批量调用现在正在开发当中。也期待师傅后续的宝贵意见😄

**Comment by JackeyLov5** [comment]
师傅们 如果可以的话能加入 result文件夹 --project project   -----> 项目文件夹/result/project 然后默认的输出文件res_alivedomain.txt 到项目文件夹/result/res_alivedomain.txt 吗？。。应用场景是 在本地使用的时候设置了 allin 环境变量res_alivedomain.txt会输出到 当前目录。我本地是改了 有时候会上传到vps来扫描 所以绝对路径确实不太好 麻烦 再次谢谢师傅们

**Comment by christasa** [comment]
AlliN有`--project`参数和`-o`参数能够指定文件输出，这两个参数是否能够满足师傅要求。或者师傅详细描述一下输出文件的需求？

**Comment by christasa** [comment]
sfscan的`-f`参数支持在这次版本中已经实现，因此关闭这个issue，再次感谢师傅的宝贵建议
