### ISSUE TITLE
刚刚使用了一下

### ISSUE THREAD

**Issue by JackeyLov5** [P1-Team/AlliN#16]
师傅们好，上次可能没描述清楚，-f选项的需求是 python allin.py -f host.txt -m fscan 或者调用其他的扫描模块，感觉实现确实有点麻烦，感觉可以把title和host查询分开或者只做txt里一列host的fofa查询语句，师傅们没时间实现也没关系，这个项目已经很好了！！还有一个问题是二进制的allin怎么配置key呢。。谢谢各位师傅

**Comment by JackeyLov5** [comment]
好的谢谢师傅解答，根据师傅的建议我也准备了sh也是个不错的方法，请问怎么才能把资产用所有扫描模块扫描出来呢？比较冒昧再问一下师傅们平时攻防用allin怎么去做扫描比较高效又全呢 谢谢师傅



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Christa ***@***.***&gt;
发送时间: 2023年6月12日 21:00
收件人: P1-Team/AlliN ***@***.***&gt;
抄送: JackeyLov5 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [P1-Team/AlliN] 刚刚使用了一下 (Issue #16)





 
因为AlliN主打的扫描，fofa只是获取URL的一个手段，且网上直接获取fofa的项目很多，GUI又做的很漂亮，不能保证能够做的非常美观，因此暂时不考虑title和host查询分开的开发。
 
二进制主要是为了解决内网扫描的时候没有Python解释器的时候带来的麻烦，是不能配置key的。在自己主机进行扫描的场景下师傅可以直接使用Python源码脚本，也更加方便的

**Comment by Like0x** [comment]
AlliN 使用分内外网情况，外网就title扫描比较多一些。内网就是各种check模块 和各种信息搜集模块的组合使用，怎么顺手怎么来。
