### ISSUE TITLE
添加指纹，中文报错

### ISSUE THREAD

**Issue by localurk** [P1-Team/AlliN#19]
自己添加指纹，"":""，第一个”“里面不能是中文，不然就报错   if self.trie[u].child[ids] == 0:
![image](https://github.com/P1-Team/AlliN/assets/13211756/ac1e811a-671d-4b4e-b427-af182bb0b609)

**Comment by christasa** [comment]
因为Python 2的Unicode编码和Python 3的不兼容，为了适配Python2。因此`self.fin`不能使用中英文结合的指纹，例如`指纹finger`，只能使用英文以及常见字符。并且`self.cfin`也只能为全中文不能中英文夹杂，但可以中文标点符号和汉子结合，例如`《指纹》`。如果需要中英文结合的判断，可以在[https://github.com/P1-Team/AlliN/blob/main/AlliN.py#L7084](https://github.com/P1-Team/AlliN/blob/main/AlliN.py#L7084) 后对resp做内容判断

**Comment by christasa** [comment]
因无后续问题，故关闭该issue
