### ISSUE TITLE
[ - ] KeyError('size')

### ISSUE THREAD

**Issue by ckx516712534** [P1-Team/AlliN#21]
运行环境python 3.9报错如下：
 Waiting for fofa ... 
[ - ] KeyError('size')
 xxxxxx（手动码）  |  PASSIVE Request error  | CERT Request  1 |  VTS Request error  | 

 [ >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ]  2/2 (100%) 0 to Go

Task completed

**Comment by christasa** [comment]
一般情况下是本地Fofa API的token不对， 或者Fofa的Email和token不匹配

**Comment by christasa** [comment]
因无后续问题，故关闭该issue
