### ISSUE TITLE
如何添加favicon.ico指纹hash信息

### ISSUE THREAD

**Issue by jiemodesehn** [P1-Team/AlliN#22]
请问如何添加favicon.ico指纹hash信息，让allin进行指纹识别

**Comment by christasa** [comment]
https://github.com/P1-Team/AlliN/blob/06ec453d6de729fbb995e75f946bdbfc12198df5/AlliN.py#L5665
在该`self.fin`字典中加上mmh3的值以及对应的指纹即可

**Comment by christasa** [comment]
因无后续问题，故关闭该issue
