### ISSUE TITLE
师傅我用脚本执行就会有这些警告信息

### ISSUE THREAD

**Issue by JackeyLov5** [P1-Team/AlliN#27]
<img width="899" alt="image" src="https://github.com/user-attachments/assets/ac05005c-3afd-453c-b7ed-b77177d2ecaf">
rm -rf ./result/res_alivedomain.txt
while read line
do
    host=`echo $line | awk -F " " '{print $1}'`
    echo $host
    python3 AlliN.py -q "(domain=\"$host\" || cert=\"$host\") &&  country=\"CN\" && region!=\"HK\" && region!=\"TW\" && region!=\"MO\"" -m sfscan
done < domain.txt
虽然不影响 但是我取值的时候会出现各种问题orz 
python运行就不会 但是基本用的时候就是批量 
我看了一下新加的那个功能-f 好像不能直接用根域名

**Comment by christasa** [comment]
大量warning是因为Python 3.12之后的正则规则改了，后续会修复。然后师傅的说的新加的功能是哪一个呀?

**Comment by JackeyLov5** [comment]
> 大量warning是因为Python 3.12之后的正则规则改了，后续会修复。然后师傅的说的新加的功能是哪一个呀?

就是-f 功能 好像也不是新功能 好像不能直接用根域名

**Comment by christasa** [comment]
`-f`要用根域名的话只能在subscan域名扫描才行，其他的功能需要保证这个域名能够被正常解析

**Comment by christasa** [comment]
warning已经去掉了，感谢师傅的提出

**Comment by JackeyLov5** [comment]
> 警告已去掉，谢谢师傅的提出

师傅太客气了 谢谢您和您的团队。还有一个点就是好像默认输出只会存在web资产。如果是批量或者fofa拉取 由于终端行数保留问题 会拿不到ip+端口 或者 域名加端口的信息呢？这个怎么处理呢
