### ISSUE TITLE
端口扫描的疑问

### ISSUE THREAD

**Issue by L-codes** [P1-Team/AlliN#3]
请问为什么端口扫描的`timeout`设置为`3.0`时(默认)，则切换为`0.5`秒？
https://github.com/P1-Team/AlliN/blob/dedd237a297a416e34ad2dc02d07a31f71a4b903/AlliN.py#L5870

**Comment by ninefiger** [comment]
不为什么

**Comment by L-codes** [comment]
老哥 你们施魔法 🪄

**Comment by christasa** [comment]
AlliN端口的扫描的场景是单个端口快速扫描大量ip，在内网的时候用的比较多。3秒延迟对于端口连接来说比较长，所以设置成啦0.5秒

**Comment by L-codes** [comment]
@christasa 跟我想的可能一样，但是建议可以添加参数设置tcp连接的timeout，如`--connect-timeout`，实在不行也应该 `psscan` 改为降低 timeout 时间，而不是直接的 3 转 0.5 的操作，因为0.5秒的操作哪怕是内网，还是大概率出现漏报的情况

**Comment by Like0x** [comment]
> @christasa 跟我想的可能一样，但是建议可以添加参数设置tcp连接的timeout，如`--connect-timeout`，实在不行也应该 `pscan` 改为降低 timeout 时间，而不是直接的 3 转 0.5 的操作，因为0.5秒的操作哪怕是内网，还是大概率出现漏报的情况

当前的逻辑会出现用户真正想要set 3的时候而出现0.5的情况，这其实是个Bug，感谢师傅提出issue。我在想这里应该单独添加一个connect-timeout的选项，因为timeout 默认是3，还是需要区分开来。

**Comment by christasa** [comment]
已在2.1.9版本解决，再次感谢指出
