### ISSUE TITLE
扫web貌似会卡在最后。。

### ISSUE THREAD

**Issue by Googuai** [P1-Team/AlliN#5]
![image](https://user-images.githubusercontent.com/41504730/145464376-a77f03c2-6792-473b-933f-4139349414ef.png)

**Comment by christasa** [comment]
老哥用的是读文件传扫描地址还是用的`--host` 传呀?

**Comment by Googuai** [comment]
> 老哥用的是读文件传扫描地址还是用的`--host` 传呀?

读文件和--host 都用了，都不行，我是扫的B段和C段，都会卡在最后一点

**Comment by christasa** [comment]
好的，将会在后面版本改进，感谢师傅指出🌹

**Comment by christasa** [comment]
以解决，感谢指出
